spring.application.name=appointment-system

# ---------- Database ----------
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# ---------- Security ----------
jwt.secret=${JWT_SECRET}

password.encoder.strength=${PASSWORD_ENCODER_STRENGTH:12}

# in millis
access.token.expiration=${ACCESS_TOKEN_EXPIRATION:600000}

# in days
refresh.token.expiration=${REFRESH_TOKEN_EXPIRATION:1}

# ---------- Bootstrap Admin ----------
app.bootstrap.admin.email=${ADMIN_EMAIL}
app.bootstrap.admin.password=${ADMIN_PASSWORD}
app.bootstrap.admin.first-name=${ADMIN_FIRST_NAME:System}
app.bootstrap.admin.last-name=${ADMIN_LAST_NAME:Administrator}

# ---------- Client ----------
client.base.url=${CLIENT_BASE_URL}

# ---------- Actuator ----------
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# ---------- Time Slot ----------
# in minutes
time.slot.duration=${TIME_SLOT_DURATION:15}
